server:
  port: 8200
spring:
  application:
    name: credit-config
  cloud:
    config:
      server:
        git:
          uri: http://git.citydo.com.cn/credit/credit-config-repo.git
          username: zuog@citydo.com.cn
          password: zuogan123
#          basedir: C:\workSpace\credit\credit-config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000ConfigApplication/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
